site_name: fetchu
site_description: Documentation for fetchu
site_author: imacodr
site_url: https://imacodr.github.io/fetchu

repo_name: imacodr/fetchu
repo_url: https://github.com/imacodr/fetchu

theme:
  logo: https://raw.githubusercontent.com/imacodr/fetchu/main/assets/logo.png
  favicon: https://raw.githubusercontent.com/imacodr/fetchu/main/assets/logo.png
  name: material
  palette:
    scheme: slate
    primary: red

nav:
  - Introduction: index.md
  - Installation: installation.md
  - API: api.md
  - Help!: help.md
