[package]
name = "imacodr/fetchu"
description = "Simplifying requests out of Roblox making HttpService easier."
version = "1.0.4"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"